### ISSUE TITLE
Aepp Authorization - Identity Management

### ISSUE THREAD

**Issue by emil-apeunit** [aeternity/aepp-prototypes#3]
**I as a user I just want to limit the amount of tokens that an æpp can spend (maybe even on a daily/weekly/monthly basis) because my trust in aepps is limited.**

Our current approach is to build a mobile app called base-aepp that manages several Identities, each Identity has it's own balance and aeternity-tokens can be transfered between Identities. The base-aepp can allow a third-party aepp full access to an identity.

We still have to develop a concept for desktop devices.

**Comment by followyoureyes** [comment]
A user doesn't want to import his private keys each time in a new stand alone app, though wants to have intance (app, chrome extension, browser) where he once signs up with his private keys, which runs in the background and which he can use to sign messages or pay for blockchain transactions/ writes.

What options do we have?

1. For mobile: Run several sub apps in **one app space** (no stand alone app)
2. For mobile / **Android**: we managed sofar to exchange some transaction information between two stand alone apps (further questions? Would this also support several wallet accounts? Will the user have to switch from one app to the other or can we display an overlay or similar in the stand alone app?)
3. For mobile: In react native (not sure how mature weex for VueJS is) he **iframe api** should work as well

4. For web: Built **one app space** where the several apps run as microservices in one app (no stand alone apps)
5. For web: **Chrome extension** like meta mask
6. For web: **iframe api** to communicate with two apps
7. For web: **own browser**

**Comment by emil-apeunit** [comment]
We have to clarify if every single transaction is approved by a base-aepp(mobile and desktop) or if the base-aepp is granting general access to an identity and aepps itself are responsible to authorize single transactions.

**Comment by emil-apeunit** [comment]
We will use the iframe api approach
