### ISSUE TITLE
Create a very basic UX design for the aeternity-wall

### ISSUE THREAD

**Issue by emil-apeunit** [aeternity/aepp-prototypes#44]
**User Stories:**
As an aeternity supporter I want to write a message into the aeternal blockchain space, to share my thoughts for now and forever
As an enthusiastic user I want to read aeternal messages because I'm interested in the aeternity community
As an aeterniy supporter I want to express my support for messages that I like

**Include functions:**
- Show messages
- Write a message 
- Like a message with an ERC20 AE-Token, this token shall be transferred to message author

Keep in mind that we might include ranking options later, keep it flexible.

**Comment by Martinhessmann** [comment]
Mentioned in #67
