### ISSUE TITLE
Design progress indicators for blockchain operations and an animation for file hash generation

### ISSUE THREAD

**Issue by emil-apeunit** [aeternity/aepp-prototypes#47]
Users upload an image and get a cryptic combination of letters and numbers as feedback.
We need an image that represents the generation of a file hash, to help users to understand what is happening and what a file hash is.

- A file hash animation
- A general progress icon

**Comment by Martinhessmann** [comment]
While the hash is generated, we want the user to watch his hash being calculated.
within 2-3 seconds the digits will count up from 0 to F in a 8x8 grid, using the roboto mono font to give it a graphical look and feel.

![calculating_hash](https://user-images.githubusercontent.com/7511610/31333184-570d6a8e-ace9-11e7-8f8a-57f889495b69.gif)


For all progresses in the conversational interface, we use the three dots in an empty speech bubble ". . ."
