### ISSUE TITLE
Connect the aepp-voting with the Identity Manager

### ISSUE THREAD

**Issue by emil-apeunit** [aeternity/aepp-prototypes#50]

**Comment by emil-apeunit** [comment]
@followyoureyes please update @knarz once you merged your PR's

**Comment by followyoureyes** [comment]
@knarz please go ahead and use the aepp-voting repo for the base app
https://github.com/aeternity/aepp-voting 

- It works for metamask and for signing with a wallet (Myether) 
- Right now as next steps only frontend changes would take place
