### ISSUE TITLE
Implement a basic version of the aeternity-wall

### ISSUE THREAD

**Issue by emil-apeunit** [aeternity/aepp-prototypes#56]
User Stories:
As an aeternity supporter I want to write a message into the aeternal blockchain space, to share my thoughts for now and forever
As an enthusiastic user I want to read aeternal messages because I'm interested in the aeternity community
As an aeterniy supporter I want to express my support for messages that I like

Include functions:
- Show messages
- Write a message
- Like a message with an ERC20 AE-Token, this token shall be transferred to message author

Keep in mind that we might include ranking options later, keep it flexible.

**Comment by knarz** [comment]
Done here https://github.com/aeternity/aepp-wall/tree/approveAndCall
