### ISSUE TITLE
Poster images aepp-voting screencast

### ISSUE THREAD

**Issue by emil-apeunit** [aeternity/aepp-prototypes#65]
We need a two poster images to advertise our HOW TO videos for the aepp-voting

**Comment by Martinhessmann** [comment]
@followyoureyes 
Use those two, and set the Playbutton and Textoverlay Color to White.

![voting_poster-metamask](https://user-images.githubusercontent.com/7511610/31346157-78df7af6-ad18-11e7-8ae3-cf492ac860da.jpg)
![voting_poster-wallet](https://user-images.githubusercontent.com/7511610/31346156-78de969a-ad18-11e7-95e6-fd0c163ba6d0.jpg)

**Comment by followyoureyes** [comment]
It's implemented and deployed
